#!/bin/sh

show_help() {
    cat <<EOF
Usage: locker [options]
Options:
    --production    Run in production mode (default: development mode)

EOF
}

locker_mode=development

# Parse command line options
while true; do
    case "$1" in
      -h|--help|-\?) show_help; exit 0;;
      --production) locker_mode=production; shift ;;
      --development) shift ;;
      --) shift; break;;
      -*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
      *)  break;;
    esac
done

# If our dependencies are installed in the source tree, find them there
. scripts/use-deps.sh

# Make sure we have some API keys, otherwise we can't do much
apikeys=Config/apikeys.json
if [ ! -f "$apikeys" ]; then
    echo "No API keys found in $apikeys" >&2
    echo "see https://github.com/LockerProject/Locker/wiki/GettingAPIKeys" >&2
    exit 1
fi

monitor() {
    # Monitor the process and restart it if it dies

    trap shutdown INT TERM
    while true; do
        start_time=$(date +%s)
        # start the command
        $* &
        lockerd_pid=$!

        if wait $lockerd_pid; then
            # Clean shutdown
            exit 0
        fi

        # Abnormal exit

        end_time=$(date +%s)
        runtime=$(($end_time - $start_time))
        if [ "$runtime" -lt 10 ]; then
            echo "locker was only running for $runtime seconds, not respawning" >&2
            exit 1
        fi

        wait=5
        echo "Locker exited unexpectedly, respawning in $wait seconds..." >&2
        sleep $wait
    done
}

shutdown() {
    kill -TERM $lockerd_pid
    wait $lockerd_pid
    status=$?
    echo "locker exited with status $status"
    exit $status
}

# Extra paths to search for files : separated
export NODE_PATH=lib:Common/node

# Start the locker
case "$locker_mode" in
    production)
        # Tell node to run in production mode
        NODE_ENV=production
        export NODE_ENV
        monitor node lockerd.js "$@"
        ;;
    development|*)
        # Just run it
        exec node lockerd.js "$@"
        ;;
esac

exit 1
