#!/bin/sh

set -e

MAKE=${MAKE:-make}
subdir="$1"
tarball="$2"

tmpdir=$(mktemp -d)
trap "rm -rf '$tmpdir'" EXIT
tar xf "$tarball" -C "$tmpdir"
cd "$tmpdir/$subdir"
if [ -n "${CONFIG_PATH}" ]; then
  echo "Setting config to ${CONFIG_PATH}"
  cp "${CONFIG_PATH}" test/resources/config.json
fi
$MAKE test
